### ISSUE TITLE
IOS location tracking bug

### ISSUE THREAD

**Issue by alexbanilean** [trifangrobert/Saferr#6]
WARN  Possible Unhandled Promise Rejection (id: 0):
Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.
Error: One of the `NSLocation*UsageDescription` keys must be present in Info.plist to be able to use geolocation.

**Comment by trifangrobert** [comment]
iOS requires special permissions for background processes, should change info.plist accordingly

**Comment by alexbanilean** [comment]
Changed the way user location is updated.
Fixed with pull request #9.
